import type { MarketingChecklist, Project, WebsiteChecklist } from "@/lib/projects/types";

/**
 * Converts a date object to ISO string.
 *
 * @param d Source date.
 * @returns ISO timestamp string.
 */
function iso(d: Date): string {
  return d.toISOString();
}

/**
 * Generates an ISO timestamp offset by N calendar days from now.
 *
 * @param days Relative day offset from current date.
 * @returns ISO timestamp string.
 */
function daysFromNow(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return iso(d);
}

/**
 * Produces a complete website checklist using defaults plus optional overrides.
 *
 * @param partial Optional override values for checklist flags.
 * @returns Fully-populated website checklist object.
 */
function baseWebsiteChecklist(partial: Partial<WebsiteChecklist>): WebsiteChecklist {
  return {
    proposalPrepared: false,
    proposalSent: false,
    proposalAccepted: false,
    contractSent: false,
    contractSigned: false,
    invoiceSent: false,
    invoicePaid: false,
    designStarted: false,
    designApproved: false,
    developmentStarted: false,
    developmentCompleted: false,
    revisionsRequested: false,
    revisionsCompleted: false,
    deployed: false,
    ...partial,
  };
}

/**
 * Produces a complete marketing checklist using defaults plus optional overrides.
 *
 * @param partial Optional override values for checklist flags.
 * @returns Fully-populated marketing checklist object.
 */
function baseMarketingChecklist(partial: Partial<MarketingChecklist>): MarketingChecklist {
  return {
    proposalPrepared: false,
    proposalSent: false,
    proposalAccepted: false,
    contractSent: false,
    contractSigned: false,
    invoiceSent: false,
    invoicePaid: false,
    strategyDefined: false,
    assetsCreated: false,
    campaignSetup: false,
    campaignLaunched: false,
    optimizationOngoing: false,
    reporting: false,
    ...partial,
  };
}

/**
 * Local seed dataset for project flows used by seed API/bootstrap scenarios.
 */
export const SEED_PROJECTS: Project[] = [
  {
    id: "p_1001",
    category: "Website",
    clientName: "Mila Petrova",
    companyName: "Bloom Dental Studio",
    projectName: "New marketing website",
    projectType: "Corporate Website",
    services: [{ name: "Website Development", category: "Web" }],
    sourceOwner: "Peter",
    status: "Proposal Sent",
    sortIndex: 0,
    startDate: daysFromNow(10),
    targetEndDate: daysFromNow(40),
    priority: "Medium",
    notes: "Requested: clean, premium look. Waiting on decision after proposal.",
    isArchived: false,
    proposalAmount: 4200,
    agreedAmount: 0,
    invoicedAmount: 0,
    paidAmount: 0,
    currency: "EUR",
    paymentStatus: "Unpaid",
    createdAt: daysFromNow(-6),
    updatedAt: daysFromNow(-1),
    checklist: baseWebsiteChecklist({ proposalPrepared: true, proposalSent: true }),
    activity: [
      {
        id: "n_2001",
        projectId: "p_1001",
        author: "Peter",
        body: "Proposal sent with 2 options (standard + premium).",
        createdAt: daysFromNow(-1),
      },
    ],
  },
  {
    id: "p_1002",
    category: "Website",
    clientName: "Viktor Iliev",
    companyName: "Nordic Sauna BG",
    projectName: "Landing page + lead form",
    projectType: "Landing Page",
    services: [{ name: "Website Development", category: "Web" }],
    sourceOwner: "Krasi",
    status: "Won",
    sortIndex: 0,
    startDate: daysFromNow(14),
    targetEndDate: daysFromNow(35),
    priority: "High",
    notes: "Won but not scheduled yet. Needs slot selection.",
    isArchived: false,
    proposalAmount: 1800,
    agreedAmount: 1800,
    invoicedAmount: 900,
    paidAmount: 0,
    currency: "EUR",
    paymentStatus: "Unpaid",
    createdAt: daysFromNow(-12),
    updatedAt: daysFromNow(-2),
    checklist: baseWebsiteChecklist({
      proposalPrepared: true,
      proposalSent: true,
      proposalAccepted: true,
      contractSent: true,
      contractSigned: true,
    }),
    activity: [
      {
        id: "n_2002",
        projectId: "p_1002",
        author: "Krasi",
        body: "Contract signed. Waiting to schedule kickoff based on current workload.",
        createdAt: daysFromNow(-2),
      },
    ],
  },
  {
    id: "p_1003",
    category: "Website",
    clientName: "Ani Georgieva",
    companyName: "Kukla Boutique",
    projectName: "E-commerce refresh",
    projectType: "E-commerce",
    services: [
      { name: "E-commerce", category: "Web" },
      { name: "UI/UX Design", category: "Design" },
    ],
    sourceOwner: "Peter",
    status: "Scheduled",
    sortIndex: 0,
    startDate: daysFromNow(3),
    targetEndDate: daysFromNow(60),
    priority: "High",
    notes: "Scheduled to start next week. Ensure discovery doc is ready.",
    isArchived: false,
    proposalAmount: 12000,
    agreedAmount: 12000,
    invoicedAmount: 6000,
    paidAmount: 6000,
    currency: "EUR",
    paymentStatus: "Paid",
    createdAt: daysFromNow(-20),
    updatedAt: daysFromNow(-3),
    checklist: baseWebsiteChecklist({
      proposalPrepared: true,
      proposalSent: true,
      proposalAccepted: true,
      contractSent: true,
      contractSigned: true,
      invoiceSent: true,
      invoicePaid: true,
    }),
    activity: [
      {
        id: "n_2003",
        projectId: "p_1003",
        author: "Peter",
        body: "Invoice paid. Scheduled start confirmed.",
        createdAt: daysFromNow(-3),
      },
    ],
  },
  {
    id: "p_1004",
    category: "Website",
    clientName: "Georgi Marinov",
    companyName: "Atlas Legal",
    projectName: "Website redesign",
    projectType: "Corporate Website",
    services: [
      { name: "Website Development", category: "Web" },
      { name: "Branding", category: "Design" },
    ],
    sourceOwner: "Team",
    status: "In Progress",
    sortIndex: 0,
    startDate: daysFromNow(-4),
    targetEndDate: daysFromNow(18),
    priority: "Urgent",
    notes: "Design is underway; client asked for a more premium tone.",
    isArchived: false,
    proposalAmount: 8500,
    agreedAmount: 8500,
    invoicedAmount: 4250,
    paidAmount: 4250,
    currency: "EUR",
    paymentStatus: "Paid",
    createdAt: daysFromNow(-25),
    updatedAt: daysFromNow(-1),
    checklist: baseWebsiteChecklist({
      proposalPrepared: true,
      proposalSent: true,
      proposalAccepted: true,
      contractSent: true,
      contractSigned: true,
      invoiceSent: true,
      invoicePaid: true,
      designStarted: true,
    }),
    activity: [
      {
        id: "n_2004",
        projectId: "p_1004",
        author: "Other",
        body: "Homepage layout v1 shared internally.",
        createdAt: daysFromNow(-1),
      },
    ],
  },
  {
    id: "p_1005",
    category: "Website",
    clientName: "Stela Yordanova",
    companyName: "Fjord Coffee Roasters",
    projectName: "Marketing site v2",
    projectType: "Corporate Website",
    services: [
      { name: "Website Development", category: "Web" },
      { name: "Google Ads", category: "Marketing" },
    ],
    sourceOwner: "Krasi",
    status: "Waiting for Client",
    sortIndex: 0,
    startDate: daysFromNow(-12),
    targetEndDate: daysFromNow(8),
    priority: "Medium",
    notes: "Waiting for client feedback on design revisions.",
    isArchived: false,
    proposalAmount: 5200,
    agreedAmount: 5200,
    invoicedAmount: 2600,
    paidAmount: 1300,
    currency: "EUR",
    paymentStatus: "Partial",
    createdAt: daysFromNow(-40),
    updatedAt: daysFromNow(-4),
    checklist: baseWebsiteChecklist({
      proposalPrepared: true,
      proposalSent: true,
      proposalAccepted: true,
      contractSent: true,
      contractSigned: true,
      invoiceSent: true,
      invoicePaid: true,
      designStarted: true,
      designApproved: false,
      revisionsRequested: true,
    }),
    activity: [
      {
        id: "n_2005",
        projectId: "p_1005",
        author: "Krasi",
        body: "Client requested adjustments to hero + typography. Awaiting approval on v2.",
        createdAt: daysFromNow(-4),
      },
    ],
  },
  {
    id: "p_1006",
    category: "Website",
    clientName: "Nikolay Dimitrov",
    companyName: "GymPro",
    projectName: "Web app MVP",
    projectType: "Custom Web App",
    services: [
      { name: "Custom Web App", category: "Web" },
      { name: "UI/UX Design", category: "Design" },
    ],
    sourceOwner: "Peter",
    status: "In Progress",
    sortIndex: 1,
    startDate: daysFromNow(-20),
    targetEndDate: daysFromNow(-2),
    priority: "Urgent",
    notes: "Dev in progress; timeline slipped due to scope creep.",
    isArchived: false,
    proposalAmount: 22000,
    agreedAmount: 22000,
    invoicedAmount: 11000,
    paidAmount: 8000,
    currency: "EUR",
    paymentStatus: "Partial",
    createdAt: daysFromNow(-70),
    updatedAt: daysFromNow(-1),
    checklist: baseWebsiteChecklist({
      proposalPrepared: true,
      proposalSent: true,
      proposalAccepted: true,
      contractSent: true,
      contractSigned: true,
      invoiceSent: true,
      invoicePaid: true,
      designStarted: true,
      designApproved: true,
      developmentStarted: true,
    }),
    activity: [
      {
        id: "n_2006",
        projectId: "p_1006",
        author: "Peter",
        body: "Backend endpoints mostly done; front-end onboarding pending.",
        createdAt: daysFromNow(-1),
      },
    ],
  },
  {
    id: "p_1007",
    category: "Marketing",
    clientName: "Todor Hristov",
    companyName: "Skyline Real Estate",
    projectName: "SEO foundation + content plan",
    projectType: "SEO",
    services: [{ name: "SEO", category: "Marketing" }],
    sourceOwner: "Team",
    status: "Blocked",
    sortIndex: 0,
    startDate: daysFromNow(-6),
    targetEndDate: daysFromNow(12),
    priority: "High",
    notes: "Blocked on content + property photos.",
    blockedReason: "Client hasn’t delivered final copy and image pack.",
    isArchived: false,
    proposalAmount: 2400,
    agreedAmount: 2400,
    invoicedAmount: 1200,
    paidAmount: 0,
    currency: "EUR",
    paymentStatus: "Unpaid",
    createdAt: daysFromNow(-30),
    updatedAt: daysFromNow(-2),
    checklist: baseMarketingChecklist({
      proposalPrepared: true,
      proposalSent: true,
      proposalAccepted: true,
      contractSent: true,
      contractSigned: true,
      invoiceSent: true,
      invoicePaid: true,
      strategyDefined: true,
    }),
    activity: [
      {
        id: "n_2007",
        projectId: "p_1007",
        author: "Other",
        body: "Blocked due to missing content assets. Sent reminder email.",
        createdAt: daysFromNow(-2),
      },
    ],
  },
  {
    id: "p_1008",
    category: "Marketing",
    clientName: "Elena Popova",
    companyName: "Aurum Clinic",
    projectName: "Facebook Ads launch",
    projectType: "Facebook Ads",
    services: [{ name: "Facebook Ads", category: "Marketing" }],
    sourceOwner: "Krasi",
    status: "Completed",
    sortIndex: 0,
    startDate: daysFromNow(-60),
    targetEndDate: daysFromNow(-20),
    priority: "Medium",
    notes: "Delivered and deployed. Keep for portfolio.",
    isArchived: false,
    proposalAmount: 3000,
    agreedAmount: 3000,
    invoicedAmount: 3000,
    paidAmount: 3000,
    currency: "EUR",
    paymentStatus: "Paid",
    createdAt: daysFromNow(-90),
    updatedAt: daysFromNow(-20),
    checklist: baseMarketingChecklist({
      proposalPrepared: true,
      proposalSent: true,
      proposalAccepted: true,
      contractSent: true,
      contractSigned: true,
      invoiceSent: true,
      invoicePaid: true,
      strategyDefined: true,
      assetsCreated: true,
      campaignSetup: true,
      campaignLaunched: true,
      optimizationOngoing: true,
      reporting: true,
    }),
    activity: [
      {
        id: "n_2008",
        projectId: "p_1008",
        author: "Peter",
        body: "Deployment completed and DNS switched.",
        createdAt: daysFromNow(-20),
      },
    ],
  },
  {
    id: "p_1009",
    category: "Marketing",
    clientName: "Daniela Ivanova",
    companyName: "Lumen Skincare",
    projectName: "Google Ads scaling",
    projectType: "Google Ads",
    services: [{ name: "Google Ads", category: "Marketing" }],
    sourceOwner: "Peter",
    status: "Scheduled",
    sortIndex: 0,
    startDate: daysFromNow(5),
    targetEndDate: daysFromNow(35),
    priority: "High",
    notes: "Scheduled start; ensure tracking + landing pages are ready.",
    isArchived: false,
    proposalAmount: 4500,
    agreedAmount: 4500,
    invoicedAmount: 2250,
    paidAmount: 0,
    currency: "EUR",
    paymentStatus: "Unpaid",
    createdAt: daysFromNow(-10),
    updatedAt: daysFromNow(-2),
    checklist: baseMarketingChecklist({
      proposalPrepared: true,
      proposalSent: true,
      proposalAccepted: true,
      contractSent: true,
      contractSigned: true,
      invoiceSent: true,
      invoicePaid: true,
    }),
    activity: [
      {
        id: "n_2009",
        projectId: "p_1009",
        author: "Peter",
        body: "Kickoff scheduled. Waiting on asset pack and tracking access.",
        createdAt: daysFromNow(-2),
      },
    ],
  },
  {
    id: "p_1010",
    category: "Marketing",
    clientName: "Kiril Stoyanov",
    companyName: "Vela Foods",
    projectName: "Social content + management",
    projectType: "Social Media Management",
    services: [{ name: "Social Media Management", category: "Marketing" }],
    sourceOwner: "Team",
    status: "Waiting for Client",
    sortIndex: 1,
    startDate: daysFromNow(-8),
    targetEndDate: daysFromNow(20),
    priority: "Medium",
    notes: "Waiting for brand assets and product photography.",
    isArchived: false,
    proposalAmount: 1600,
    agreedAmount: 1600,
    invoicedAmount: 800,
    paidAmount: 0,
    currency: "EUR",
    paymentStatus: "Unpaid",
    createdAt: daysFromNow(-22),
    updatedAt: daysFromNow(-3),
    checklist: baseMarketingChecklist({
      proposalPrepared: true,
      proposalSent: true,
      proposalAccepted: true,
      contractSent: true,
      contractSigned: true,
      invoiceSent: true,
      invoicePaid: true,
      strategyDefined: true,
    }),
    activity: [
      {
        id: "n_2010",
        projectId: "p_1010",
        author: "Team",
        body: "Requested product photos + updated brand kit. Content calendar draft ready.",
        createdAt: daysFromNow(-3),
      },
    ],
  },
];

